### PR TITLE
Django deprecations and Python 3+

### PR DESCRIPTION
**Pull request by adelq**
Upgrade to latest Django before 2.0 and finalize Python 3.0 compatibility. This should be released and deployed as a Python 3 app to test stability before moving forward with Django 2.0.

### CODE REVIEW

**Comment by adelq** [comment]
Upgrading to `django-registration==2.3` blocked on https://github.com/ubernostrum/django-registration/issues/122

**Comment by adelq** [comment]
Upgrading to `django-localflavor >= 1.4` blocked due to deprecation warning (and eventual deprecation of) `USPhoneNumberField`, which is the only part of `django-localflavor` that we use. They suggest to use https://github.com/stefanfoulis/django-phonenumber-field, but it's incredibly poorly documented.

Long term, we should probably just copy this specific field into our codebase to avoid technical debt.

**Comment by ezwang** [comment]
Maybe we could just use a CharField with a RegexValidator?

https://stackoverflow.com/a/19131360

**Comment by adelq** [comment]
That's essentially how it's implemented in `django-localflavor`:
https://github.com/django/django-localflavor/blob/4a855051c3433e57970fd7d9ed940e0d333531c1/localflavor/us/forms.py#L46-L62

**Pull request merged**
